urfit-tech/lodestar-app

src/components/checkout/CheckoutProductModal.tsx
@kkshyu  please merge this branch before verifying other payment gateway
this error may cause the perpetual payment gateway to always be `spagateway` when buying physical goods <(_ _)>
=> [BUGFIX] add payment to place order

src/components/program/ProgramContentPlayer.tsx, src/pages/ActivityCollectionPage.tsx
這 PR 解掉底下這兩個 issue
1. 在播放時調快倍速後，跳到其他秒數，會變回原本的倍速
2. 調左右鍵控制播放軸，音量會變回初始值
順便 refactor 一下 localStroage 相關程式碼，換成統一的 function
在移動時間軸的時候會觸發 canPlay 事件，就執行到了：
``` js
player.volume(config.volume)
player.playbackRate(config.playbackRate)
```
這時候的 config 是舊的，所以就用到舊的值了，就會回復成 1
目前解法是傳入 getConifg function 取代原本使用的 config，在要使用時從 localStorage 去拿，就能保證結果正確。VimeoPlayer 我就先沒調整了，一樣是用 config，想說這應該未來也會棄用，先保證現有行為就好。
=> [BUGFIX] fix player volume and playback rate bug

src/components/sale/OrderCollectionAdminCard.tsx, src/components/sale/OrderStatusTag.tsx, src/helpers/translation.ts
- show repay button when order status is one of 'UNPAID', 'PARTIAL_PAID', 'FAILED'
- translate new order status, error code
=> [FEATURE] translation of new order status

package.json, yarn.lock
Issue: screen capture doesn't contain background image in some cases. 
According to the issue report in https://github.com/niklasvh/html2canvas/issues/1544#issuecomment-435640901
It seems like a cache issue, which need to update `html2canvas` source code. 
I have forked the repo and patched, migrate to use the patched version and see if this issue could be resolved.
Patch: https://github.com/jhihruei/html2canvas/commit/1911b3ffebf24256f7a3fc9f471484131443b691
=> [FIX] hot-fix html2canvas CORS issue

src/pages/MerchandiseCollectionPage.tsx
- Not filter by `isPhysical` when querying merchandises.
- Because we need the whole merchandises list to know if they have virtual/physical merchandises and we only fetch data once for now, we should not filter merchandises by `isPhysical`.
- Reset categoryId when selected tab changed. 
- The category might not always existing in both virtual and physical merchandises, we should reset category to avoid listing nothing after switch different tabs.
- Hide RadioCard (virtual/physical tabs) when the merchandises only contain one of them. 
- Make the `isPhysical` in query string no work, if the  merchandises only contain one of virtual/physical.
=> [FEATURE] merchandise list only display RadioCard when having different types 

src/components/blog/PostCover.tsx, src/components/blog/PostLinkCollection.tsx, src/pages/BlogPostPage/BlogPostPage.tsx
=> [UPDATE] Adjust PostCover position and image size

src/components/blog/PostCover.tsx, src/pages/BlogPostPage/BlogPostPage.tsx
- Video
- Image with (almost) expected ratio
- Image with unexpected ratio (1:1)
----
- Video
- Image with (almost) expected ratio
- Image with unexpected ratio (1:1)
----
- Video
- Image with (almost) expected ratio
- Image with unexpected ratio (1:1)
=> [BUGFIX] Fix post cover image ratio and video preview size

src/pages/AppPage/index.tsx, src/pages/ProgramPage/index.tsx
- only craft page directly use `PageHelmet` component
- send event when setting is loaded
=> [BUGFIX] prevent sending unneeded titleChange event

src/hooks/program.ts
目前後台管理介面沒有調整順序的功能，應該單純看 created_at 就足夠
看起來問題應該是 order_by 的 rules 不正確而已
=> [BUGFIX] Fix program roles ordering

src/pages/AppPage/index.tsx
This reverts commit a583534481b55687fe5ce1893ab6bae6590a8963.
我改回原本的寫法歐 ～
這個 branch 在做的事情，只是讓有開 「裝置管理」 或 「登入上限」模組的客戶
在換頁的時候額外檢查當前的裝置有沒有被強制登出，因此只要去判斷 refresh token 回來的狀態是否為 success
如果不是的話需要把當前的 authtoken 清空 讓他登出
補充：原本 refresh token 只有在重整頁面、導向網站(例如：第一次進入網站、從其他金流頁面導回 lodestar) 的時候會去呼叫(可參考 [lodestar-app-element](https://github.com/urfit-tech/lodestar-app-element/blob/master/src/contexts/AppContext.tsx#L163-L168) )
=> Revert "fix: update token"

src/components/blog/FeaturingPostItem.tsx, src/components/blog/PostItemCollection.tsx, src/components/blog/index.tsx, src/pages/BlogPage.tsx, src/pages/BlogPostCollectionPage.tsx
1.黑色遮罩拉高一點，調整成background-image: linear-gradient(rgba(0, 0, 0, 0) 25%, black)
2.標題變粗、下間距縮成4px
3.下方區塊的標題統一改顯示兩行
4.分類的設定
5.手機版標題設定
=> [Bugfix] Blog detail style udpate

src/containers/program/ProgramCard.tsx, src/hasura.d.ts, src/types/program.ts
舊的方式：拿完全部的課程資料，進入課程內容頁不需再載入
新的方式：拿完所需的課程資料，進入課程內容頁再去拿該課程的全部資料
原本 src/containers/program/ProgramCard.tsx 用的是 useProgram
但其實根本不需要取那麼多資料
所以改寫成新的 useProgramPreview
=> [BUGFIX] fix MemberPage load ProgramCard slowly

src/hooks/data.ts, src/hooks/practice.ts, src/hooks/program.ts
- insert attachment once to avoid null `attachment.data`
=> fix: attachment null data

src/pages/AppPage/CraftBlock.tsx
- modify anchor default scroll position is top of CraftBlock
requirement:
頁面網址：
後台：https://www.xuemi.co/admin/craft-page/efced959-0b28-4ed9-8043-83324e752d8e
前台：https://www.xuemi.co/faq#faq-solve
敘述：使用錨點功能當區塊太長就會滑到正中間而不是該區塊的上方，尤其是這個區塊線上課程疑難排解（會滑到中間），詳見附圖
=> fix: modify anchor default scroll position is top of CraftBlock

src/components/layout/DefaultLayout/index.tsx
requirement:
控制「我的主頁」字詞顯示： nav.my_page.name
ZZ已設定，但前台卻沒改變QQ
https://www.dogtorstray.com/
bug reason:
我之前再做合併的時候把自訂的我的主頁和創作者業給蓋過去了
所以導致修改參數設定 nav.my_page.name 的時候會無效
=> fix: add custom my page name & creator page name

src/components/podcast/PodcastProgramPopover.tsx, src/hooks/podcast.ts, src/pages/PodcastProgramCollectionPage.tsx
- add podcast not individually sale condition
requirement:
前台的部份，當無單集銷售時，點選單集音頻，應該要讓「立即購買」與「加入購物車」區域直接 display: none; 。
https://samplepage.kolable.app/podcasts
=> feat: add podcast not individually sale condition

package.json, src/components/checkout/CheckoutBlock.tsx, yarn.lock
1. notice that '付款方式' ‘我同意’ wouldn't keep data after user reload the page.
2. add 'kolable.checkout.approvement' to LocalStorage to store the value.
3. add lodestar-app-element #2445c245d1ac7e2e95f726e4aca60159eca45945 to the repo, to fix  '付款方式''s problem
=> fix: resolve cached data in cart

src/pages/BlogPostCollectionPage.tsx
requirement: 「在 blog 的頁面中，封面圖片的 div 寬高和建議尺寸不合。建議尺寸是 1200 \ *675，也就是 width * 0.5625，但是不知道為什麼元件的寫法是 width * 0.6666666。這邊需要協助修正。」
1. modify the variant of component PostPreviewCover
variant: “list-item“ → “featuring“
=> fix: modify picture size in BlogPostCollectionPage

src/contexts/PodcastPlayerContext.tsx
- modify PodcastPlayerContext play mode
requirement:
專輯：
https://demo.lodestar-dev.cc/podcast-albums/dd54e5a5-b99b-46fa-80d0-5ee64a4c2eb9
單曲：
https://demo.lodestar-dev.cc/podcasts/349d2a83-a3c8-4286-af56-e0cf0156f2cd
經測試後
✅ 單曲循環
❌ 全部循環 ➡️ 單曲時，此全部循環 icon 應持續循環，但直接停止；不過專輯時會持續全部循環
->幫改為只有單曲時，就循環那一個單曲
❌ 隨機播放 ➡️ 專輯多曲時，隨機播放 icon，但疑似沒有隨機，播完直接停止，但偶有會有繼續播放； 單曲時，直接停止
https://drive.google.com/file/d/1Cq_PH6m3p0Z3RCRbyy9jic0v7A7y0bu_/view?usp=drive_link
->幫改為只有單曲時，就隨機那一個單曲
->幫檢查專輯多曲時，隨機播放要可以正常運行，協助解決播放完停止的問題
=> fix: modify PodcastPlayerContext play mode

package.json, src/hooks/data.ts, src/hooks/voucher.ts, yarn.lock
requirement:
誤發或是需收回權益時可以「註銷」
目前大多情況是使用在退款註銷券、發錯註銷券
且都是隨機碼的情況，比較會有需要註銷券的需求
實作
https://zpl.io/bzgKX13
邏輯如下：
0.請實作於後台折價方案、兌換方案兩個地方
https://demo.lodestar-dev.cc/admin/voucher-plans
https://demo.lodestar-dev.cc/admin/coupon-plans
1.當折價、兌換碼不論為自訂碼或隨機碼時，有出現刪除鈕可以註銷。
2.註銷請做成軟刪除 deleted_at，且不可再被他人使用
3.已被用過的碼，且訂單為「非已完成」（付款中、已完成不可註銷），可以註銷碼。
不管有無被歸戶(歸戶後未使用)，可刪除。
4.按註銷刪除鈕後
若可刪除：會出現系統提示modal，用系統預設的樣式就好
文案：確定要註銷此代碼 CY77-WPDP-B7N 嗎？註銷後將移除此代碼使用權
[取消][確定]
刪除，該碼會直接從後台消失user端也是
若不可刪除：會出現系統提示modal，用系統預設的樣式就好
文案：此代碼 CY77-WPDP-B7N 已被使用，如需註銷請確認該筆訂單狀態為已退款
[確定]
=> fix: add deleted_at is null in GET_COUPON_COLLECTION & GET_ENROLLED_VOUCHER_COLLECTION

.vscode/settings.json, src/pages/MemberPage/index.tsx, src/pages/ProgramContentPage/index.tsx
requirement:
Hubspot chat出現在學米無限我的主頁、學習區的右下角
我們目前是用GTM裝，常被學生說卡卡，使用者體驗不好，KK說要換其他寫法
希望能優先處理
有時第一次進入頁面hubspot那顆不會正常出現，重整才出現
note: sixdigital use core
=> feat: add HubSpot chat in MemberPage & ProgramContentPage

src/components/common/OverviewBlock.tsx
Card:
```
需求
創作者頁面點擊單一位創作者後，會進入到個人創作者頁面
「我的作品」頁面右側的「開設課程」在沒有開設課程的狀態下，應隱藏或寫判斷該位對象是否有開設課程，有開課程的才顯示，沒有開課的就隱藏，避免誤會
https://www.credits.cc/creators/
➡️ 有開課程的才顯示，沒有開課的就隱藏
參考：
https://www.credits.cc/creators/c092b0cb-6499-432b-a120-576c391d5667
```
=> feat: programs length less than zero hide block

src/components/appointment/AppointmentItem.tsx, src/components/appointment/AppointmentPeriodCollection.tsx, src/hooks/appointment.ts, src/pages/CreatorPage.tsx, src/types/appointment.ts
Card:
```
預約方案>>銷售方案>>單場人數上限>>不設限
會員可以重複預約同一天同一時段的諮詢，一個帳號同一時段應該只能預約一次
```
- Additional change: Matching default component name with file naming.
=> fix: same member appointment

src/components/appointment/AppointmentPeriodCollection.tsx
Issues:
When `period.currentMemberBooked` is true for the AppointmentItem, the style is displayed in a disabled state, but the appointment modal can still be opened by clicking.
Reason:
The component requires an additional wrapping `<div>` layer and the use of onClick return to effectively disable it.
Adjustment:
As mentioned above, the adjustment adds an additional wrapping `<div>` to the component and utilizes onClick return to achieve the desired disabling effect effectively.
Card message :
```
只有畫面看起來「已預約」
實際上卻還是可以點擊….
要disabled才對
```
=> fix: isEnrolled AppointmentItem onClick

package.json, src/components/project/FundingIntroductionPane.tsx, src/pages/ActivityPage/ActivityPage.tsx, src/pages/ProgramPackagePage/ProgramPackagePage.tsx, src/pages/ProgramPage/index.tsx, src/pages/ProjectPage/FundingPage.tsx, src/styles.scss, yarn.lock
- 請調整為 會不會爆版 為判斷，而不以類型區分
- 在沒有爆版的情況下，方案區塊的操作如
- 在爆版的情況下，方案區塊的操作如目前課程一樣，卡片無需固定https://www.cwlearning.com.tw/programs/d4427286-6739-4953-b56d-8b2ace59024b?visitIntro=1
- 註：爆版的定義為超出螢幕畫面中可呈現的範圍
- 需實作在課程簡介、課程組合、專案、活動
- 留意天下課程簡介有魔改，他要適用之外其他標準客戶也須適用此邏輯
ZZ留存：https://docs.google.com/document/d/14pZj5FxEISPqfzvYwPnn2LWxOHMWNb4_NH4dxDwXFso/edit
調整「課程頁」、「課程組合頁」、「專案頁」和「活動頁」結構
並在各個產品的方案區塊加上「positionSticky」的 className
用於滾動後固定住產品方案列
=> feat: add product page's plan list block can fixed

src/components/voucher/VoucherCollectionBlock.tsx, src/hooks/voucher.ts
Replaced GraphQL queries in the `useEnrolledVoucherCollection` hook with axios calls and context-based authentication to improve reliability. Data fetching is now more efficient and aligned with the new authorization standards. Additionally, replaced the `useQuery` hook with custom state management and fetch function to better handle loading and error states. This change streamlines the process of fetching enrolled vouchers by utilizing the RESTful endpoint and managing state explicitly within the hook.
=> refactor: voucher hook to use axios

src/hooks/data.ts, src/pages/member/CouponCollectionAdminPage.tsx, src/types/checkout.ts, src/types/coupon.ts
Replaced GraphQL coupon fetching with a RESTful API call to handle coupon collection data retrieval in `useCouponCollection`. This shifts data fetching to rely on a new endpoint provided by the Lodestar API. The client now uses Axios for handling HTTP requests and manages state with `useState`, `useEffect`, and `useCallback` hooks to better handle async operations. Removed redundant fields ('count' and 'remaining') from the `CouponProps` type definition. The consuming component `CouponCollectionAdminPage` also has updated props to align with the hook's new return values.
This change improves data consistency by centralizing the source of coupon data and simplifies the data-fetching logic, streamlining client-side state management.
=> refactor: coupon fetching to use external API

src/components/checkout/CheckoutBlock.tsx
- remove default address prefix
- If isOutsideTaiwanIsland is 'true', it will automatically clear the values of 'zipCode', 'city', and 'district'.
=> bugfix: remove address prefix

src/components/package/ProgramPackageCollectionBlock.tsx, src/containers/program/EnrolledProgramCollectionBlock.tsx
What
---
- Because in the process of solving the demand, I saw an no search message when not searching, so I corrected it.
=> fix: display noSearchEnrolledProgram and noSearchEnrollProgramPackage message condition

src/components/audio/GlobalAudioPlayer.tsx, src/components/audio/PlaylistOverlay.tsx, src/contexts/AudioPlayerContext.tsx, src/pages/ProgramContentPage/ProgramContentBlock.tsx, src/types/program.ts
Title: Fix iOS Commute Mode Playback Issue and Update AudioPlayerContext
Description:
Objective (WHY):
To restore the normal functionality of the commute mode for iOS users and enhance the audio player's integration with the backend, ensuring smooth and reliable usage.
Current Issue:
On iOS devices, switching to commute mode results in an unresponsive player, indicated by a perpetual loading spinner. This issue affects users under the following conditions:
Device: iPhone 11
OS Version: 16.11
Browser: Safari
Modifications Made:
AudioPlayerContext.tsx: Integrated new API calls to lodestar-server, enhancing the AudioPlayerContext to better manage state and dependencies across different components and network conditions.
ProgramContentPlayer.tsx: Updated to utilize the enhanced …
=> fix: video background mode cannot play

src/components/ebook/EbookReaderControlBar.tsx, src/components/program/ProgramContentEbookReader.tsx, src/components/program/translation.ts, src/hooks/ebook.ts, src/pages/ProgramContentPage/ProgramContentBlock.tsx, src/pages/ProgramPage/Primary/ProgramContentListSection.tsx, src/pages/ProgramPage/Secondary/SecondaryProgramContentListItem.tsx, src/translations/locales/en-us.json, src/translations/locales/id.json, src/translations/locales/vi.json, src/translations/locales/zh-cn.json, src/translations/locales/zh-tw.json
- The conditions for completing the trial reading of the e-book are:
- `contentType` is e-book.
- `displayMode` is `trial` or `loginToTrial`.
- `sliderPercentage` is greater than or equal to `ebookTrialPercentage`.
- Add `CommonModal` to `ProgramContentEbookReader` and display it when the e-book trial is completed.
- Disable the right page turning behavior when the e-book trial is completed.
- Move `sliderOnChangeEnd` to `onChange` and rename it to `handleSliderChange` to fix the bug of page jumping when turning pages.
- Add isEnrolled of `ProgramContentItem` in `ProgramContentListSection` as a condition for previewing e-books to fix the display bug where the mouse finger does not appear.
=> feat: ProgramContentEbookReader add trialComplete

src/components/program/ProgramContentEbookReader.tsx, src/pages/ProgramPage/Ebook/EbookProgramPageContent/index.tsx
- There is no response when clicking the "Trial" button in EbookProgramPageContent and the "Buy Now" button in the window that appears after the trial is completed.
- First, find the first unit that matches the displayMode of "Trial" or "loginToTrial" and the contentType of ebook, and add the link component of chakra-ui outside the "Trial" button in EbookProgramPageContent. When clicked, the link to the above qualified unit is triggered.
- Add the Link Component of chakra-ui outside the "Buy Now" button and link it to the program intro page.
=> feat: EbookProgramPageContent trial button link and purchase button link

src/pages/ProgramPage/Ebook/EbookProgramPageContent/index.tsx
- Adjust `EbookProgramPageContent` `isHasEbookTrialSection` display trial button.
- `Image` component change to `Box` component with backgroundImage by `EbookProgramPageContent`'s cover.
- When `coverUrl` is empty, the cover of `EbookProgramPageContent` is `EmptyCover`.
=> fix: adjust EbookProgramPageContent isHasEbookTrialSection display trial button and Image change to backgroundImage

src/pages/ProgramPage/Secondary/SecondaryProgramBanner.tsx
修正課程名稱在手機版畫面被截斷的問題，讓完整名稱可以正常顯示。
- Trello 卡片：https://trello.com/c/jyNQ82TN
=> fix: fix truncated course title on mobile view

src/components/checkout/CheckoutBlock.tsx
=> fix:setting checkout.approvement boolean and numeric flag recognition
