urfit-tech/lodestar-app

src/components/appointment/AppointmentCollectionTabs.tsx
src/components/appointment/AppointmentPeriodCollection.tsx
src/hooks/appointment.ts
src/types.d.ts
src/types/appointment.ts

[(2) 【預約】補上提前預約功能+排解時段碰撞](https://trello.com/c/CJXkJWKW)

[FEATURE] appointment dismiss the period which can not reserve

---

src/components/auth/AuthModal.tsx

if `authState` is `register`,  let `maskClosable`  is false

[FEATURE] add mask closable to AuthModal

---

src/Application.tsx
src/components/common/ApplicationHelmet.tsx
src/components/program/ProgramContentBlock.tsx
src/components/program/ProgramContentPlayer.tsx
src/containers/common/AppContext.tsx
src/helpers/index.ts
src/hooks/util.ts
src/styles.scss

[FEATURE] add swarmify including captions, watermark and video CDN

---

src/components/activity/ActivityBanner.tsx
src/components/common/BlurredBanner.tsx
src/components/common/CreatorIntroBlock.tsx
src/components/common/podcastAlbum/PodcastAlbumBanner.tsx
src/components/package/ProgramPackageBanner.tsx
src/components/program/ProgramCard.tsx
src/containers/program/ProgramCard.tsx
src/hasura.d.ts
src/hooks/program.ts
src/pages/ProgramPage/ProgramBanner/CustomizeProgramBanner.tsx
src/pages/ProgramPage/ProgramBanner/PerpetualProgramBanner.tsx
src/pages/SearchPage.tsx
src/types/program.ts
yarn.lock

+ change ProgramCard thumbnail and cover display logic

[FEATURE] program can display different cover

---

src/hasura.d.ts
src/hooks/blog.ts
src/pages/BlogPostPage/BlogPostPage.tsx
src/types/blog.ts

[FEATURE] show source in post page

---

src/pages/ProgramPackageContentPage.tsx
src/pages/ProgramPackagePage.tsx

+ program pakage add target and rel attribute

[FEATURE] add _blank

---

src/pages/AdvancedSearchPage.tsx

+ add is_private is false
+ add is_deleted is false

[BUGFIX] if program is private , hide the program

---

src/helpers/translation.ts
src/pages/PaymentTaskPage.tsx
src/pages/translation.ts

[BUGFIX] payment error message

---

src/hasura.d.ts
src/pages/OrderPage.tsx

- add a delayed job to sync payment when user enter OrderPage

[FEATURE] add a sync payment task

---

src/pages/PaymentTapPayPage.tsx

- redirect according to api's response

[BUGFIX] redirect according to api's resonse

---

src/components/sale/OrderCollectionAdminCard.tsx
src/hasura.d.ts
src/pages/OrderPage.tsx

- move delayed job from orderPage to OrderCollectionAdminCard

[BUGFIX] move delayed job from orderPage to OrderCollectionAdminCard

---

src/components/activity/ActivityTicketPaymentButton.tsx
src/components/common/PaymentButton.tsx
src/components/merchandise/MerchandisePaymentButton.tsx
src/pages/ProgramPage/ProgramPlanCard/ProgramPlanPaymentButton.tsx

- tracking merchandise spec addToCart event
- use find instead of filter to avoid ts noUncheckedIndexedAccess bug

[BUGFIX] merchandise spec addToCart tracking

---

src/components/merchandise/MerchandisePaymentButton.tsx
src/helpers/translation.ts
src/translations/locales/acsi.json
src/translations/locales/en-us.json
src/translations/locales/id.json
src/translations/locales/vi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

- add not enough coins message
- add coin checking status

[BUGFIX] add-not-enough-coins-message

---

src/pages/ProgramPage/ProgramContentListSection.tsx

How to verify:
- Without logged in, go to http://localhost:3333/programs/7ca21659-f825-4220-8cad-2d5b93dc42b7?visitIntro=1
- Scroll to any video and click
- login 
- After logged in, it should auto-scroll to previous position

[FEATURE] Scroll to previous position after logged in

---

package.json
src/components/auth/LoginSection.tsx
yarn.lock

The major reason of this issue is that lodestar-app-element handle the error instead of throw. After update element package, make it throw the error directly, we could get the error message and handle it as our expected.

[BUGFIX] Fix login error message not translated

---

package.json
yarn.lock

Only update package to apply bug fix.
After this PR https://github.com/urfit-tech/lodestar-app-element/pull/49 merged, if there is another commit/PR updated lodestar-app-element, then this PR could be closed directly.

[BUGFIX] Update lodestar-app-element to apply fix

---

src/pages/MerchandiseCollectionPage.tsx

I'm not sure if there is any naming convention or coding style guide, just try to improve the readability. 
If only need one of the commits, please let me know (or cherry-pick to another PR is okay).
- Rename variable to avoid confusing.
- Use enum instead of string

[REFACTOR] Rename variables and use enum

---

src/components/common/PageHelmet.tsx
src/hasura.d.ts
src/pages/AppPage/index.tsx
src/types/metaTag.ts

[FEATURE] add SEO & Open Graph tags in custom page

---

src/helpers/translation.ts
src/hooks/task.ts
src/pages/OrderTaskPage.tsx
src/translations/locales/acsi.json
src/translations/locales/en-us.json
src/translations/locales/id.json
src/translations/locales/vi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

Add missing E_QUEUE error message translation.  
Add code handling at OrderTaskPage.

[Bugfix] Task job error present

---

package.json
src/components/auth/RegisterSection.tsx
src/components/checkout/CheckoutBlock.tsx
src/components/checkout/CouponInsertionCard.tsx
src/components/checkout/ShippingInput.tsx
src/components/voucher/VoucherInsertBlock.tsx
src/pages/ForgotPasswordPage.tsx
yarn.lock

- 登入
- [existing] account
- 註冊
- [existing] username
- [existing] email
- [new] signup_info form
- [existing] SMS phone number
- [new] SMS verification code
- 忘記密碼
- [new] email
- 折價券 (/settings/coupons)
- [new] 新增折價券
- 兌換券 (/settings/voucher)
- [new] 新增兌換券
- 結帳頁 (/cart)
- 寄送資訊
- [new] 姓名
- [new] 電話
- [new] 地址(僅有文字輸入的部分，不含選單)
- [new] 備註
- 發票 -> 個人
- [new] 自然人憑證條碼
- [new] 手機條碼
- 統一編號
- [new] 統一編號
- [new] 發票抬頭
- [new] 選擇折價券 -> 輸入折扣碼
- [new] 推薦人信箱
NOTE: 
[new] -> 本次有修改的欄位
[existing] -> 原先就有做的欄位

[FEATURE] Trim Input fields

---

src/components/checkout/CheckoutBlock.tsx
src/components/checkout/ShippingInput.tsx

+ hide the shipping method radio and skip shipping verify if outlying islands

[BUGFIX] fix isOutsideTaiwanIsland validate logic

---

src/components/common/PageHelmet.tsx
src/helpers/index.ts
src/pages/AppPage/index.tsx
src/pages/BlogPostPage/BlogPostPageHelmet.tsx
src/pages/ProgramPackagePage/ProgramPackagePageHelmet.tsx
src/pages/ProgramPage/ProgramPageHelmet.tsx

- fix & refactor page seo and og settings

Bugfix/fix & refactor page seo and og settings

---

src/components/auth/LoginSection.tsx
src/helpers/translation.ts
src/styles.scss

In this version, you have to install latest element from https://github.com/urfit-tech/lodestar-app-element/pull/65

fix: remove check device logic

---

src/components/notification/NotificationItem.tsx
src/helpers/index.ts

- add portfolio marked notification

[BUGFIX] add portfolio marked notification

---

src/components/checkout/CheckoutBlock.tsx
src/components/checkout/ShippingInput.tsx

-fix default city selector does not save zip code

[BUGFIX] fix default city selector dosen't save zip code

---

package.json
yarn.lock

We're going to allow user to edit the block-quote text-align, so remove this hardcoded align

Change: Remove hardcoded block quote align

---

src/components/merchandise/MerchandiseBlock.tsx
src/hasura.d.ts
src/hooks/merchandise.ts

- get merchandise spec quantity in need

[BUGFIX] get merchandise spec quantity in need

---

src/components/program/ProgramContentMenu.tsx
src/helpers/index.ts
src/helpers/translation.ts
src/hooks/program.ts
src/pages/ProgramContentPage/ProgramContentBlock.tsx
src/pages/ProgramContentPage/translation.ts
src/pages/ProgramPage/ProgramContentListSection.tsx
src/translations/locales/acsi.json
src/translations/locales/en-us.json
src/translations/locales/id.json
src/translations/locales/vi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

- modify Program Intro Page
- modify Program Conetent Page

[BUGFIX] modify Program Intro Page & Program Conetent Page

---

src/components/checkout/CouponInsertionCard.tsx
src/components/voucher/VoucherInsertBlock.tsx

- add auto fill in coupon code & voucher code

[FEATURE] add auto fill in coupon code & voucher code

---

src/hasura.d.ts
src/hooks/program.ts
src/pages/ProgramPage/ProgramPlanCard/index.tsx
src/types/program.ts

- add enrollment count in program plan

[BUGFIX] add enrollment count in program plan

---

src/pages/ActivityPage/ActivityPageHelmet.tsx
src/pages/ProgramContentPage/ProgramContentPageHelmet.tsx
src/pages/ProgramPackagePage/ProgramPackagePageHelmet.tsx
src/pages/ProgramPage/ProgramPageHelmet.tsx
src/pages/ProjectCollectionPage/ProjectCollectionPageHelmet.tsx
src/pages/ProjectPage/ProjectPageHelmet.tsx

[BUGFIX] modify product page helmet

---

src/components/profile/ProfileBasicAdminCard.tsx

[BUGFIX] Fix incorrect data format of BraftEditor

---

src/hasura.d.ts
src/pages/ProgramContentPage/ProgramContentBlock.tsx

- fix exam & practice no display UnpublishedBlock

[BUGFIX] fix exam & practice no display UnpublishedBlock

---

src/components/common/ApplyTagModal.tsx
src/hasura.d.ts
src/hooks/common.ts
src/pages/ProjectPage/PortfolioPage.tsx
src/types/project.ts

[BUGFIX] modify PortfolioPage

---

src/components/blog/index.tsx

[BUGFIX]Blog title style change 

---

src/components/blog/PostItemCollection.tsx
src/pages/CreatorPage.tsx

【個人專頁】個人專頁要顯示「作品」tab，裡面呈現我發布的作品與被標記的作品＋個人專頁沒有內容的項目不要出現tab

[bugfix] create page tab setting

---

package.json
src/hasura.d.ts
src/hooks/program.ts
src/pages/ProgramPage/index.tsx
yarn.lock

- add trigger program view increase

[FEATURE] add trigger program view increase

---

src/hasura.d.ts
src/pages/ProjectPage/PortfolioPage.tsx
src/pages/ResetPasswordPage.tsx
src/pages/translation.ts
src/types/project.ts

+ let project portfolio participant can set password in ResetPasswordPage.
+ change participant tag style

Project portfolio participant

---

src/hasura.d.ts
src/hooks/member.ts
src/pages/CreatorPage.tsx
src/pages/SearchPage.tsx
src/types/member.ts

+ SearchPage, can search backstage_enter general-member if app has setting `search.general_member_result.enabled`
+ CreatorPage, adjust NotFoundPage logic

[FEATURE] adjust SearchPage and CreatorPage

---

src/components/profile/ProfileOtherAdminCard.tsx
src/hasura.d.ts

1. 新增await setting
2. 修改GQL錯字問題
3. 新增disable 設定

[Bugfix] member field change

---

src/helpers/translation.ts

feat: coupon error code

---

src/components/auth/LoginSection.tsx

use `lodestar-app-element` commit `43efc2b` to return error object

fix: error class

---

src/components/blog/FeaturingPostItem.tsx
src/components/blog/PostPreviewMeta.tsx
src/pages/BlogPostCollectionPage.tsx
src/pages/BlogPostPage/BlogPostPage.tsx

- add author link in blog
- fix BlogPostCollectionPage author link is covered by div onClick event

fix: add author link in blog

---

src/components/checkout/CouponAdminCard.tsx
src/components/voucher/Voucher.tsx
src/components/voucher/VoucherCollectionTabs.tsx
src/containers/voucher/VoucherCollectionBlock.tsx
src/helpers/translation.ts
src/pages/member/CouponCollectionAdminPage.tsx
src/translations/locales/en-us.json
src/translations/locales/id.json
src/translations/locales/vi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

- add "used" status tab in coupon
- add "notYet" & "used" status in vouchar
- add CouponCollectionAdminPage loading view
- modify CouponAdminCard styles

fix: modify coupon & voucher tabs

---

src/hooks/program.ts
src/pages/ProgramContentPage/ProgramContentBlock.tsx

- modify insert program progress logic
- fix infinitely re-render from refetchProgress
- modify publishedAt from useProgramContent

fix: modify ProgramContentBlock

---

src/pages/CartPage.tsx

+ multiple product type
- has merchandise_spec，display choss cart，multiple CartProductTableCard
- merchandise_spec is none，display CheckoutBlock
+ url has `shopId` query param，display merchandies's merchandise_spec
+ url doesn't have `shopId` query param，display none merchandise_spec product
+ product is none

fix: shop id query param

---

src/components/common/AudioPlayer.tsx
src/components/common/VideoPlayer.tsx
src/contexts/MediaPlayerContext.tsx
src/helpers/index.ts
src/pages/ProgramContentPage/ProgramContentBlock.tsx

- fix azure video does not play in background mode
- add mimeType condition in audioPlayer for hls

fix azure video does't play in background mode

---

src/hooks/data.ts
src/pages/ContractPage.tsx

feat: add contract name, email

---

src/hooks/data.ts

- Add member name when properties value is null in contract

feat: add member name when properties value null

---

src/pages/TermsPage.tsx

- modify TermsPage app name
```
const { name, settings } = useApp()
const appName = settings['name'] || name
```

fix: modify TermsPage app name

---

src/hooks/program.ts

1. modify program_isIssuesOpen Logic in Program.ts

fix: modify program_isIssuesOpen logic

---

src/pages/ProgramPage/ProgramContentListSection.tsx

1. when program contentType is "text", show "試看"(trial) instead of "試聽"(audioTrial)

fix: trial and audioTrial

---

src/pages/member/CoinHistoryAdminPage.tsx

fix: order by created

---

src/components/profile/ProfileOtherAdminCard.tsx

- modify member property field required rule
requirement:
客戶於後台新增的自訂欄位，並標註為必填
但前台並沒有顯示必填，需請 FA 協助查看是什麼狀況，可以怎麼處理，感謝

fix: modify member property field required rule

---

src/components/common/LikedCountButton.tsx
src/pages/ProjectPage/PortfolioPage.tsx

- modify PortfolioPage tags
requirement:
這兩個作品都無法在前台顯示「大兼製作」，但其他的正常顯示
前台：https://www.credits.cc/projects/2220bd76-5b65-4886-bbb9-fbc98b47c260
後台：https://www.credits.cc/admin/projects/2220bd76-5b65-4886-bbb9-fbc98b47c260?tab=management
前台：https://www.credits.cc/projects/82b8b47f-9b16-4c90-a222-4ec5760f7a97
後台：https://www.credits.cc/admin/projects/82b8b47f-9b16-4c90-a222-4ec5760f7a97?tab=management
正常顯示標籤：
前台：https://www.credits.cc/projects/414846d3-c43a-417a-a417-baa78d92b96c
後台：https://www.credits.cc/admin/projects/414846d3-c43a-417a-a417-baa78d92b96c?tab=management

fix: modify PortfolioPage tags

---

src/components/program/ProgramContentMaterialBlock.tsx
src/hooks/program.ts

+ insert material_audit_log when download

feat: record  material download log

---

src/hooks/common.ts

1. fix title without program_package.title in cart to make title more clear

fix: fix title in cart

---

src/components/layout/DefaultLayout/index.tsx

1. add 'entry_page.first_method' in setting and app_setting.
2. if customer's 'entry_page.first_method' is 'register', show register page after customer click 'cartSubmit' button.

feat: modify login to register page by customer

---

package.json
src/components/checkout/CheckoutBlock.tsx
yarn.lock

https://github.com/urfit-tech/lodestar-app-element/commit/c7f63f16d473be187941f99a2ca38c031bc947fb

fix: default payment value

---

src/pages/MeetingPage/MeetingPage.tsx

1. add 'inbound_英鎊' in 廣告素材  after submitting meetus page if appId equals 'sixdigital'.
2. refactor code to insert 'inbound_英鎊'

feat: add inbound after submitting meetus page

---

src/components/common/PageHelmet.tsx
src/pages/CreatorPage.tsx

ref: https://developers.google.com/search/docs/crawling-indexing/block-indexing?hl=zh-tw

feat: meta tag can add noindex

---

src/pages/ProgramPage/ProgramContentListSection.tsx

Card:
```
前台：https://www.fschool.vip/programs/777c29d5-0532-49b6-8124-6c32015b9a92
後台：https://www.fschool.vip/admin/programs/777c29d5-0532-49b6-8124-6c32015b9a92?tab=general
1.
如果設置，僅顯示試看章節，且沒有設定任何單元為試看的話
會發生如截圖般的奇怪畫面
小章節都隱藏，大標題還在
希望調整為，課程簡介直接不顯示「課程內容」整個區塊
2.
當只有一個單元設為試看時，該章節名稱、單元要正常顯示
```

feat: program trial length less than zero hide title

---

package.json
src/pages/MeetingPage/MeetingPage.tsx
yarn.lock

Card
```
(1)頁面網址：https://www.ooschool.cc/meets/@cherry
這是透過學米的版本調的
設定上：業務專屬連結：@ 後面是學米帳號
(2)用途：無限的業務可以傳此連結去拉MGM使用
我有用我的cherry@xuemi.co 填寫一次的預約連結
但我沒有看到待辦事項生成～
這一個功能需要增加！(ps 學米的正常)
他主要是偵測 "帳號" 去抓哪一個業務ID
待辦事項就會直接下給他~~
我的CRM：https://www.ooschool.cc/admin/members/ca9f60b0-c1d6-4fa5-8163-a016b0a1fc10/profile
-
https://app.hubspot.com/contacts/41219621/record/0-5/1851837839
```

fix: MeetingPage login meet

---

src/components/appointment/AppointmentCard.tsx
src/components/appointment/AppointmentPeriodCollection.tsx

Reverts urfit-tech/lodestar-app#418

Revert "fix: appointment display"

---

src/pages/SearchPage.tsx

+ search page filter program package is private

feat: filter program package is private

---

src/hooks/program.ts

[trello](https://trello.com/c/m9vq0B8b)
由於 舊的測驗模組在被關掉後，沒辦法在前台隱藏，故需要在撈取program相關資料時，去判斷module的權限
1. 取得module的權限 const { enabledModules } = useApp()
2. 提供需要判斷是否有權限的模組 const allowedModulesArray = ['exercise']
3. 判斷權限 getModulePermission
- 只判斷allowedModulesArray有記載的模組
- 其他一率回傳 true

feat: add exercise permission judgement to program content

---

src/hooks/program.ts

[關閉作業模組後需將所有課程單元為「作業」隱藏起來](https://trello.com/c/OaaN5xMY)
[關閉測驗模組後需將所有課程單元為「測驗」隱藏起來](https://trello.com/c/m9vq0B8b)

feat: hide-exam-and-practice

---

src/hooks/voucher.ts
src/types/vouchers.ts

Simplified voucher data fetching logic by consolidating the request parameters and removing redundant filtering and mapping code in the voucher hook. Introduced a new 'VoucherFromLodestarAPI' type to streamline data processing and ensure type safety. This change enhances code maintainability and aligns the voucher data structure with the updated API schema, improving data handling efficiency and reliability.

refactor: Refactor voucher data fetching and add types

---

src/pages/TermsPrivacyPage.tsx

bugfix: Modify Title

---

yarn.lock

fixbug: reset previous package(html2canvas)

---

src/components/common/InAppBrowserWarningModal.tsx

Add a new conditional statement to prevent duplicate notifications.

bugfix: Fix the issues raised in the two notifications.

---

src/components/program/ProgramDisplayedListItem.tsx

feat: add math floor to view rate

---

src/components/ebook/EbookStyledModal.tsx

https://github.com/urfit-tech/lodestar-app/assets/107536598/d912608f-2b4c-41e7-871c-be70c581ea0e

feat: Change ebook theme button appearance and functionality

---

src/helpers/translation.ts
src/pages/ProgramContentPage/index.tsx
src/translations/locales/acsi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

feat: Update translation for common.button.list and adjust margin

---

src/components/program/ProgramContentMenu.tsx
src/contexts/ProgressContext.tsx
src/hooks/exam.ts
src/hooks/practice.ts
src/types/exam.ts

課程進度 ( program progress ) 依照課程單元 (program_content) 的個別進度 (progress) 加總後平均
+ 單元進度, content progress
+ video, audio, text
依照 program_content_progress 找到對應的 progress
+ exam, exercise
依照分數, 若滿分則 progress = 1, 若不滿分則 progress = 0.5, 若未作答則 progress = 0
+ practice
有寫作業有1, 沒有就0
+ ebook
依照 toc(章節) 的 progress 算平均

fix: distinguish progress for different types of courses

---

src/pages/ProgramContentPage/ProgramContentBlock.tsx

- permission unlocking issue resolved
- fixing multiple request loading issue

fixbug:permission unlocking issue resolved

---

src/hooks/program.ts
src/images/pin-v-2.svg
src/pages/ProgramPage/ProgramContentListSection.tsx
src/types/program.ts

- course content list expansion feature

feat:course content list expansion feature

---

src/pages/MeetingPage/MeetingPage.tsx

- Fixed an issue where prompt messages were not displayed when required fields in MeetingPage had no value.

fix: adjust MeetingPage isRequire message

---

.env.development
src/hooks/program.ts

- add functionality to retrieve membership card plan

feat:add functionality to retrieve membership card plan

---

src/components/layout/DefaultLayout/index.tsx

feat: remove-picture-url-from-jwt-token

---

src/hooks/program.ts
src/pages/ProgramPage/index.tsx
src/types/program.ts

1.  table: program / column: display_header & display_footer
2. navigate to ProgramPage and check whether is expected or not

feat: setting display layout

---

src/hooks/program.ts

fix: hook useProgramContentById

---

src/pages/member/CoinHistoryAdminPage.tsx

Making negatives and decimals allowed on coin admin page with chips showing negative coins colored yellow

feat: making negatives and decimals allowed on coin admin page with chips showing negative coins colored yellow

---

src/components/activity/ActivitySessionItem.tsx

修復浮點數顯示
顯示為 沒有小數點
測試網址：
http://localhost:3333/activities/c5bf3940-e4a2-440f-bc6c-76ffdbf4f3b0

feat: use parsefloat

---

src/hooks/program.ts

feat: adjust GetProgramPlans order_by position

---

src/components/checkout/CartProductItem.tsx
src/components/common/ProductItem.tsx

fix: the course bundle thumbnail issue

---

src/pages/ProgramPage/Secondary/SecondaryProgramPageContent/index.tsx

fix: program intro preline

---

src/components/audio/GlobalAudioPlayer.tsx
src/contexts/MediaPlayerContext.tsx
src/contexts/ProgressContext.tsx
src/pages/ProgramContentPage/ProgramContentBlock.tsx
src/pages/ProgramContentPage/ProgramCustomContentBlock.tsx

- insertProgress graphql -> lodestar-server progress api
- add progress data to player event logging

track program progress / add progress tracking to player event logging / use progress api

---

src/hooks/program.ts
src/pages/ProgramPage/ProgramPageContent.tsx
src/pages/ProgramPage/Secondary/SecondaryProgramInfoCard.tsx
src/pages/ProgramPage/index.tsx
src/types/program.ts

- use program activated_layout_template_config_id to judge which template in use 
- use new template config data type to refactor secondary template

Refactor program layout template

---

src/components/review/ReviewModal.tsx
src/pages/ProgramPage/Ebook/EbookProgramPageContent/index.tsx
src/pages/ProgramPage/Secondary/SecondaryProgramPageContent/index.tsx

- Add ReviewCollectionBlock to EbookProgramPageContent and SecondaryProgramPageContent

feat: EbookProgramPageContent and SecondaryProgramPageContent add ReviewCollectionBlock

---

src/pages/ProgramPage/Ebook/EbookProgramPageContent/index.tsx
src/pages/ProgramPage/Secondary/SecondaryInstructorCollectionBlock/CollapseContentBlock.tsx

fix programs link podcast link in template layout

feat: update button text and program link href in components

---

src/services/cart/CartOperator.ts

Show the number of carts added when not logged in.

feat: updating cart products based on login status

---

src/components/checkout/CartProductGiftPlan.tsx
src/components/checkout/CartProductItem.tsx
src/components/checkout/CartProductTableCard.tsx
src/helpers/index.ts
src/hooks/common.ts

Use `JSON.stringify` to avoid re-rendering.

fix: effect dependencies

---

src/pages/ProgramPage/Secondary/Banner/VideoBanner.tsx
src/pages/ProgramPage/Secondary/Banner/index.tsx

feat: video banner with relative length to make the ratio fixed

feat: video banner with relative length to make the ratio fixed

---

src/components/membershipCard/MembershipCardAdminBlock.tsx
src/components/membershipCard/MembershipCardBlock.tsx
src/hooks/card.ts
src/pages/member/CardCollectionAdminPage.tsx

The expiration date of the set validity period needs to be displayed next to the membership card in the order, like the equity period for courses/projects

feat: add membership card startedAt & endedAt

---

src/pages/ProgramPage/index.tsx

feat: add program page helment

---

src/components/program/ProgramCard.tsx
src/components/review/ReviewCollectionBlock.tsx
src/components/review/ReviewMemberItemCollection.tsx
src/components/review/ReviewModal.tsx
src/components/review/ReviewPublicItemCollection.tsx
src/components/review/ReviewScorePanel.tsx
src/components/review/ReviewScoreStarRow.tsx
src/helpers/translation.ts
src/translations/locales/en-us.json
src/translations/locales/id.json
src/translations/locales/ja.json
src/translations/locales/ko.json
src/translations/locales/vi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

Feat: hidable review or score sections

Feat: hidable review or score sections

---

src/components/checkout/CheckoutCard.tsx
src/components/checkout/CheckoutCardDetailCard.tsx
src/pages/OrderPaymentPage.tsx

fix: checkout card details corresponding with payment

fix: checkout card details corresponding with payment

---

src/components/common/CreatorCard.tsx

講師介紹下方的四個連結，可依設定關閉。
沒有設定時，預設是全部顯示

feat: add setting toggle for CreatorCard items

---

src/pages/ProgramPage/Secondary/Banner/PictureBanner.tsx
src/pages/ProgramPage/Secondary/Banner/VideoBanner.tsx
src/pages/ProgramPage/Secondary/SecondaryProgramBanner.tsx
src/pages/ProgramPage/Secondary/SocialSharePopover.tsx

feat: fix ratio of secondary program banner to 21:9 with some optimization on rwd.

feat: fix ratio of secondary program banner to 21:9 with some optimization on rwd

---

src/components/common/PageHelmet.tsx

feat: add dns prefetch tags in page helmet

feat: add dns prefetch tags in page helmet

---

src/components/auth/RegisterSection.tsx
src/pages/AppPage/index.tsx
src/types/tracking.ts

`tracking.register.event` change to `tracking.event`

feat: rename tracking event

---

src/hooks/data.ts
src/pages/OrderPaymentPage.tsx

If the membership type is "B" or "G" (already contracted)
- The contract section will not be displayed on the payment method page.  
- Users can proceed with checkout without signing, as there is no contract section available for signing.

feat: tli member type contract logic

---

src/pages/ProgramContentPage/ProgramContentBlock.tsx
yarn.lock

1. add ContentWrapper
2. use `program_content.dragging_right_click.disabled` setting to control feature
3. disable right-click menu, image dragging, and text selection
https://trello.com/c/dasOhMGS

feat: disable image dragging and right-click in BraftEditor

---

src/translations/locales/en-us.json

更換membership card => member card

fix:change en translation of membership card

---

src/components/audio/AudioPlayer.tsx

修正播放器控制區會遮擋畫面左下角 X（關閉）按鈕的問題。
- Trello 卡牌：https://trello.com/c/YrAxpG2F

fix: prevent player controls from covering close button

---

src/components/checkout/CartProductItem.tsx
src/components/common/ProductItem.tsx

correct display logic when listPrice is 0

fix:list price is 0

---

src/components/checkout/CheckoutBlock.tsx
src/helpers/translation.ts
src/translations/locales/de-de.json
src/translations/locales/en-us.json
src/translations/locales/id.json
src/translations/locales/ja.json
src/translations/locales/ko.json
src/translations/locales/vi.json
src/translations/locales/zh-cn.json
src/translations/locales/zh-tw.json

feat: replace i18n for cart checkout of Agree

---

src/services/cart/CartOperator.ts

fix:product enable add to cart
